<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>AICA_Client</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>  
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="modules\**" />
    <Compile Remove="ModuleTest\**" />
    <EmbeddedResource Remove="modules\**" />
    <EmbeddedResource Remove="ModuleTest\**" />
    <None Remove="modules\**" />
    <None Remove="ModuleTest\**" />
    <Page Remove="modules\**" />
    <Page Remove="ModuleTest\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="modules\CustomControl\CustomControl.csproj" />
    <ProjectReference Include="modules\SentenceManager\SentenceManager.csproj" />
    <ProjectReference Include="modules\VocabNote\VocabNote.csproj" />
    <ProjectReference Include="modules\WordSearch\WordSearch.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="WordSearch">
      <HintPath>modules\WordSearch\bin\Debug\net8.0-windows\WordSearch.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
